from app.config.config import (
    GEE_SERVICE_ACCOUNT,
    GEE_PRIVATE_KEY,
)

PROJECT_ID = "thefirstproject-496908"

SERVICE_ACCOUNT = GEE_SERVICE_ACCOUNT

PRIVATE_KEY = GEE_PRIVATE_KEY

SENTINEL_COLLECTION = "COPERNICUS/S2_SR_HARMONIZED"

LANDSAT_COLLECTION = "LANDSAT/LC08/C02/T1_L2"

SENTINEL_BANDS = [
    "B4",
    "B3",
    "B2",
    "B8",
]

THERMAL_BAND = "ST_B10"